export const ACCENT = '#5dcaa5';
export const BG = '#0b0b15';
export const SURFACE = '#13131f';
export const BORDER = '#1e1e30';
const FONT_STACK = "'Geist Mono', 'SF Mono', 'Fira Code', ui-monospace, monospace";

export const s = {
    root: { display: 'flex', minHeight: '100vh', backgroundColor: BG, fontFamily: FONT_STACK, color: '#ccc' },
    sidebar: { width: '240px', minWidth: '240px', backgroundColor: SURFACE, borderRight: `1px solid ${BORDER}`, display: 'flex', flexDirection: 'column', position: 'sticky', top: 0, height: '100vh' },
    backBtn: { display: 'flex', alignItems: 'center', gap: '10px', background: 'none', border: 'none', padding: '20px 18px', cursor: 'pointer', color: '#aaa', fontSize: '11px', fontFamily: FONT_STACK },
    backArrow: { fontSize: '16px', color: ACCENT },
    sidebarDivider: { height: '1px', backgroundColor: BORDER },
    sideSection: { padding: '16px 0' },
    sideSectionLabel: { fontSize: '10px', fontWeight: '700', letterSpacing: '0.12em', textTransform: 'uppercase', color: '#444', padding: '0 18px 8px', margin: 0 },
    sideSectionItems: { display: 'flex', flexDirection: 'column' },
    sideItem: { display: 'flex', alignItems: 'center', background: 'none', border: 'none', padding: '10px 18px', cursor: 'pointer', textAlign: 'left', width: '100%', position: 'relative', fontFamily: FONT_STACK },
    sideItemActive: { backgroundColor: 'rgba(93,202,165,0.08)' },
    sideItemLabel: { fontSize: '13px', color: '#ddd', flex: 1 },
    sideItemDot: { width: '5px', height: '5px', borderRadius: '50%', backgroundColor: ACCENT },
    main: { flex: 1, display: 'flex', flexDirection: 'column', minWidth: 0 },
    controlBar: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '16px 32px', borderBottom: `1px solid ${BORDER}`, backgroundColor: SURFACE, position: 'sticky', top: 0, zIndex: 10, gap: '16px', flexWrap: 'wrap' },
    sportsTabs: { display: 'flex', gap: '4px', backgroundColor: BG, padding: '4px', borderRadius: '8px', border: `1px solid ${BORDER}` },
    tabButton: { background: 'none', border: 'none', padding: '6px 16px', borderRadius: '6px', color: '#888', fontSize: '12px', fontWeight: '650', cursor: 'pointer', transition: 'all 0.15s', fontFamily: FONT_STACK },
    tabButtonActive: { backgroundColor: SURFACE, color: ACCENT, boxShadow: '0 2px 4px rgba(0,0,0,0.2)' },
    dropdownGroup: { display: 'flex', gap: '8px', alignItems: 'center' },
    subBar: { display: 'flex', alignItems: 'center', gap: '12px', padding: '12px 32px', borderBottom: `1px solid ${BORDER}`, backgroundColor: BG },
    select: { padding: '8px 16px', borderRadius: '6px', border: `1px solid ${BORDER}`, background: BG, color: '#fff', fontSize: '12px', fontFamily: FONT_STACK, cursor: 'pointer' },
    selectCompact: { padding: '8px 12px', borderRadius: '6px', border: `1px solid ${BORDER}`, background: BG, color: '#888', fontSize: '12px', fontFamily: FONT_STACK },
    teamSearchRow: { display: 'flex', gap: '8px', alignItems: 'center' },
    input: { padding: '8px 12px', borderRadius: '6px', border: `1px solid ${BORDER}`, background: SURFACE, color: '#ccc', fontSize: '12px', fontFamily: FONT_STACK, width: '180px' },
    fetchBtn: { padding: '8px 14px', borderRadius: '6px', border: `1px solid ${BORDER}`, background: 'none', color: ACCENT, fontSize: '12px', fontFamily: FONT_STACK, cursor: 'pointer' },
    emptyState: { flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '80px 32px', gap: '12px' },
    emptyIcon: { fontSize: '48px', opacity: 0.2 },
    emptyTitle: { fontSize: '14px', color: '#555', margin: 0 },
    loadingMsg: { color: '#555', fontSize: '13px', padding: '40px 32px' },
    errorMsg: { color: '#f06b6b', fontSize: '13px', padding: '40px 32px' },
    empty: { color: '#555', fontSize: '13px', padding: '40px 0', textAlign: 'center' },
    dataWrap: { padding: '28px 32px', flex: 1, overflowY: 'auto' },
    table: { width: '100%', borderCollapse: 'collapse', fontSize: '13px' },
    th: { backgroundColor: SURFACE, color: ACCENT, padding: '10px 14px', fontSize: '11px', fontWeight: '700', letterSpacing: '0.06em', textTransform: 'uppercase', borderBottom: `1px solid ${BORDER}` },
    td: { padding: '10px 14px', color: '#aaa', borderBottom: `1px solid ${BORDER}` },
    tdTeam: { padding: '10px 14px', display: 'flex', alignItems: 'center', gap: '10px', color: '#fff', borderBottom: `1px solid ${BORDER}` },
    rowEven: { backgroundColor: 'transparent' },
    rowOdd: { backgroundColor: 'rgba(255,255,255,0.015)' },
    icon: { width: '20px', height: '20px', objectFit: 'contain', flexShrink: 0 },
    matchCard: { background: SURFACE, border: `1px solid ${BORDER}`, borderRadius: '8px', padding: '14px 18px' },
    matchTeams: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '8px' },
    matchTeam: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '6px', fontSize: '12px', fontWeight: '500', color: '#ddd', flex: 1, textAlign: 'center' },
    matchIcon: { width: '28px', height: '28px', objectFit: 'contain' },
    matchScore: { fontSize: '22px', fontWeight: '600', color: '#fff', minWidth: '60px', textAlign: 'center' },
    matchMeta: { fontSize: '11px', color: '#444', marginTop: '10px', textAlign: 'center' },
    badgePlan: { display: 'inline-block', padding: '2px 8px', borderRadius: '99px', fontSize: '10px', fontWeight: '600', background: 'rgba(93,202,165,0.1)', color: ACCENT },
    badgeDone: { display: 'inline-block', padding: '2px 8px', borderRadius: '99px', fontSize: '10px', fontWeight: '600', background: BORDER, color: '#555' },
    scorerList: { display: 'flex', flexDirection: 'column' },
    scorerRow: { display: 'flex', alignItems: 'center', gap: '14px', padding: '11px 0', borderBottom: `1px solid ${BORDER}` },
    scorerRank: { fontSize: '12px', color: '#444', width: '24px', textAlign: 'center', fontVariantNumeric: 'tabular-nums' },
    scorerName: { fontSize: '14px', color: '#ddd' },
    scorerTeam: { fontSize: '11px', color: '#555', marginTop: '2px' },
    scorerGoals: { fontSize: '18px', fontWeight: '600', color: ACCENT, width: '40px', textAlign: 'right', fontVariantNumeric: 'tabular-nums' }
};